name: example
description: Example app
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  postgres: ^2.4.1+2
  uuid: ^3.0.4
  logging_appenders: ^1.0.0
  postgres_utils:
    path: ../
