name: example
description: Example app
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  postgres: ^3.2.0
  uuid: ^4.4.0
  logging_appenders: ^1.0.0
  postgres_utils:
    path: ../
