name: postgres_utils
description: A starting point for Dart libraries or applications.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  quiver: ^3.0.0
  meta: ^1.3.0
  clock: ^1.1.0
  logging: ^1.0.0
  postgres: ^2.3.0
  json_annotation: ^4.0.1

dev_dependencies:
  json_serializable: ^4.1.0
  pedantic: ^1.11.0
  test: ^1.16.8
  build_runner: ^1.10.0
