name: postgres_utils
description: A few utils for working with postgresql databases.
version: 1.0.0
homepage: https://github.com/authpass/postgres_utils.dart
issue_tracker: https://github.com/authpass/postgres_utils.dart/issues

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  quiver: ^3.0.0
  meta: ^1.3.0
  clock: ^1.1.0
  logging: ^1.0.0
  postgres: ^2.3.0
  json_annotation: ^4.0.1

dev_dependencies:
  json_serializable: ^5.0.0
  pedantic: ^1.11.0
  test: ^1.16.8
  build_runner: ^2.1.2
